package gamemodel;


public enum GameQuestion {
	SELECT_COUNCIL_PRIVILEGE,
	SELECT_A_DIFFERENT_COUNCIL_PRIVILEGE, 
	VATICAN_SUPPORT, 
	SELECT_PERMANENT_EFFECT,
	LEADER,
	SELECT_ACTION_SPACE, 
	HOW_MANY_FMS, 
	SELECT_PAY_METOD,
	CHOOSE_FAMILY_MEMBER;
	SELECT_EXCHANGE;
}
