package gamemodel.permanenteffect;

public enum PEffect {
	DEBUFF_RESOURCE,
	DEBUFF_POINT,
	MOD_FORZA,
	DISCOUNT,
	FM,
	HALVE_SERVANTS,
	NO_ACTION_SPACE,
	NO_MATTER_IF_OCCUPIED,
	NO_BONUS,
	NO_VICTORY_POINTS_BOUNDED_TO_CHARACTER_CARDS,
	NO_VICTORY_POINTS_BOUNDED_TO_VENTURE_CARDS,
	NO_VICTORY_POINTS_BOUNDED_TO_TERRITORY_CARDS,
	LOSE_ONE_VICTORY_POINT_FOR_EVERY_FIVE_VICTORY_POINT,
	LOSE_ONE_VICTORY_POINT_FOR_EVERY_MILITARY_POINT,
	LOSE_ONE_VICTORY_POINT_FOR_EVERY_WOOD_AND_STONE_ON_YOUR_BUILDINGS_CARDS_COST,
	LOSE_ONE_VICTORY_POINT_FOR_EVERY_RESOURCE, 
	NO_FIRST_ACTION;
}

